name: Deploy to Firebase on commit to main
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "$FIREBASE_CONFIG_B64" | base64 -d > firebase-config.json
        env:
          FIREBASE_CONFIG_B64: ${{secrets.FIREBASE_CONFIG_B64}}
      - run: |
          npm ci
          npm run build
          npm run gen-icons
      - run: |
          npx firebase deploy --only hosting,firestore:rules --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
